---
- hosts: vulnboxes
  # if you need to read some variables from the commandline at runtime of the playbook:
  # vars_prompt:
  #   - name: var_name
  #     prompt: "<PROMPT_TEXT>"
  #     # indicate if the input should be hidden or not (default is yes)
  #     private: no
  #   - name: second_var
  #     prompt: "PROMPT_TEXT2"


  tasks:
    # Create directory structure for our patches (/patches/<servicename>)
    # TODO: enable the entry for your service if you patch

    #- name: Create Patch Directory for MENSAAR
    #  file: 
    #    path: /patches/mensaar
    #    state: directory
    #    owner: root
    #    group: root

    #- name: Create Patch Directory for SAARLENDAR
    #  file: 
    #    path: /patches/saarlendar
    #    state: directory
    #    owner: root
    #    group: root

    #- name: Create Patch Directory for SAARSCHLEIFE
    #  file: 
    #    path: /patches/saarschleife
    #    state: directory
    #    owner: root
    #    group: root
    
    #- name: Create Patch Directory for SAARXIV
    #  file: 
    #    path: /patches/saarxiv
    #    state: directory
    #    owner: root
    #    group: root

    #- name: Create Patch Directory for SCHLOSSBERG
    #  file: 
    #    path: /patches/schlossberg
    #    state: directory
    #    owner: root
    #    group: root

    #- name: Create Patch Directory for STAHL4
    #  file: 
    #    path: /patches/stahl4
    #    state: directory
    #    owner: root
    #    group: root

    #- name: Create Patch Directory for LETS_SCHWENKRYPT
    #  file: 
    #    path: /patches/lets_schwenkrypt
    #    state: directory
    #    owner: root
    #    group: root


    - name: Copy Patch File
      copy: # more information on this module can be found here https://docs.ansible.com/ansible/latest/modules/copy_module.html
        # The src is the local filepath (relative from the playbook location)
        # TODO: enter your patch-file
        src: "CHANGE-ME"
        # dest is the remote path where the file should be stored
        # please follow the pattern "/patch/<servicename>/apply-patchname.sh"
        dest: "CHANGE-ME"
        owner: root
        group: root
        mode: "755"
        # if a file is overwritten create a backup of the old one first
        backup: yes
         
        # If needed the following options exist:
        # remote_src can be used to indicate that the src path is a remote path. This can be used to e.g. copy files on the remote from one location to another
        # remote_src: yes
        # content can be used instead of src to write directly into a new file. A local file can also be used as input by using functions from the templating engine (e.g. {{ lookup('file', '<local_file>') }})
        # content: "string"
